-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 11:47:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre_Usuario` VARCHAR(45) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Nombre_Colegio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Curso` VARCHAR(45) NULL,
  `Duracion` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `idUsuario`),
  INDEX `fk_Curso_Usuario_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_Curso_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modulos` (
  `idModulos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Modulo` VARCHAR(45) NOT NULL,
  `Fecha_Inicio` DATE NOT NULL,
  `idUsuario` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idModulos`, `idUsuario`, `idCurso`),
  INDEX `fk_Modulos_Usuario1_idx` (`idUsuario` ASC) ,
  INDEX `fk_Modulos_Curso1_idx` (`idCurso` ASC) ,
  CONSTRAINT `fk_Modulos_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modulos_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avance` (
  `idAvance` INT NOT NULL AUTO_INCREMENT,
  `Avance_Modulo` DOUBLE NOT NULL,
  `Avance_Clase` DOUBLE NOT NULL,
  `idUsuario` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idModulos` INT NOT NULL,
  PRIMARY KEY (`idAvance`, `idUsuario`, `idCurso`, `idModulos`),
  INDEX `fk_Avance_Usuario1_idx` (`idUsuario` ASC) ,
  INDEX `fk_Avance_Curso1_idx` (`idCurso` ASC) ,
  INDEX `fk_Avance_Modulos1_idx` (`idModulos` ASC) ,
  CONSTRAINT `fk_Avance_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avance_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avance_Modulos1`
    FOREIGN KEY (`idModulos`)
    REFERENCES `mydb`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clases` (
  `idClases` INT NOT NULL,
  `Numeracion` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `idModulos` INT NOT NULL,
  `idAvance` INT NOT NULL,
  PRIMARY KEY (`idClases`, `idModulos`, `idAvance`),
  INDEX `fk_Clases_Modulos1_idx` (`idModulos` ASC) ,
  INDEX `fk_Clases_Avance1_idx` (`idAvance` ASC) ,
  CONSTRAINT `fk_Clases_Modulos1`
    FOREIGN KEY (`idModulos`)
    REFERENCES `mydb`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clases_Avance1`
    FOREIGN KEY (`idAvance`)
    REFERENCES `mydb`.`Avance` (`idAvance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
